### DISCUSSION TITLE
an `hx-swap` option to target attributes rather than content

### DISCUSSION THREAD

**Discussion by j-n-f** [bigskysoftware/htmx#2946] [Ideas]
**tl;dr** - I'd like a version of `hx-swap`/`hx-swap-oob` that targets a node's attributes without having to change/update its contents.

**edit:** A working prototype in extension form is [here](https://github.com/bigskysoftware/htmx/discussions/2946#discussioncomment-10863071)

---

I'm developing techniques to make gracefully degrading apps without having to create multiple templates.

Imagine a page which has a left and right panel:

```
.----------------.----------------------------------------.
|                |                                        |
|                |                                        |
|    Listing     |                Details                 |
|                |                                        |
|                |                                        |
|________________|________________________________________|
```

If we assume the happy path, the markup (ignoring CSS) might look something like:

```html
<!-- I'll explain this below -->
<div id="js"></div>
<!-- what you would expect -->
<div id="item-browser">
    <ul id="item-list">
        <li><a href="/item/1" hx-get="/item/1" hx-target="#item-details">Item 1</a></li>
        <li><a href="/item/2" hx-get="/item/2" hx-target="#item-details">Item 1</a></li>
        <li><a href="/item/2" hx-get="/item/3" hx-target="#item-details">Item 1</a></li>
        <!-- so on -->
    </ul>
    <div id="item-details">
    </div>
</div>
```

The user clicks on a link in the left pane:

* **JS Enabled:** The item details will appear in the right-side pane (`hx-get` + `hx-target`)
* **JS Disabled:** The browser will navigate to the detail page (`href`)

There's only one downside: the page looks kind of goofy to a non-JS user (there's a panel that doesn't do anything). It would be ideal if the pane for item details didn't display until it was reasonably certain that the user had JS enabled.

On the backend side, we can look for the `HX-Request` header, and any time we see it we can send back a fragment after the usual content:

```html
<!-- usual content of the response -->
<div id="js" class="confirmed" hx-swap-oob="true"></div>
```

The `#js` div can be combined with CSS to control content on the rest of the page:

```css
#item-details {
    /* Initial assumption: we don't know if the user has JS */
    display: none;
}

/* assume #js is an earlier sibling of elements where we want to consider JS support */
#js.confirmed + #item-browser #item-details {
    display: unset;
}
```

Now it's possible to give a good experience to both JS/non-JS users without having to create two copies of the template. The fragment that does the OOB update can be part of a middleware in your application so individual route handlers don't have to care about JS support.

The only possible improvement from here would be to avoid having to use the sibling selector.

Imagine if that same OOB fragment could do:

```html
<body class="js" hx-swap-oob="attributesAdd"></body>
```

HTMX would take all the attributes in the fragment, and add them to the target (probably merging in this case, but you could imagine `attributesReplace` as well).

Now your CSS selectors could look like:

```css
#item-details {
    /* Initial assumption: we don't know if the user has JS */
    display: none;
}

/* We have less work to do because we were able to directly change
 * the attributes on an existing element without having to worry
 * about its content. */
.js #item-details {
    display: unset;
}
```

To recap on the benefits of this approach:

1. Write your templates once, individual templates don't have to care about general concerns (graceful degredation) in their specific context (i.e. DRY)
2. Achieve graceful degradation by having `href` for non-JS, and `hx-get` for JS
3. Templates can display differently based on attributes of containing elements (i.e. leverage CSS selectors)
4. No need for complicated client-side tests; if `HX-Request` comes in, we can be almost 100% certain that we can provide the upgraded experience
5. No need to re-render content which is already present (e.g. in the example above, without the ability to swap attributes we'd have to re-render the entire page just to update the `<body>` tag); i.e. save bandwidth and _maybe_ DOM update time.

The ability to swap attributes (either with `hx-swap` or `hx-swap-oob`) probably has more applications I haven't thought of.

The only question I have now is: could this cause any problems?
