### ISSUE TITLE
Event `revealed` is triggered if element with `display: none` is outside viewport

### ISSUE THREAD

**Issue by tilman151** [bigskysoftware/htmx#3130]
If the `hx-trigger="revealed"` is set and the CSS for the element is `display: none`, the event is triggered immediately, even though, the element is not inside the viewport.

Example (https://jsfiddle.net/5eyhfpLd/):

```html
<script src="https://demo.htmx.org"></script>

<div>
  <p id="output">
  </p>
  <div class="big">
  </div>
  <div class="indicator" hx-get="/foo" hx-trigger="revealed" hx-target="#output">
    I am the indicator!
  </div>
</div>

<template url="/foo" delay="500">
    "Reveal triggered!"
</template>
```

```css
.big {
  background-color: orange;
  height: 110vh;
}

.indicator {
  display: none;
}

.indicator.hx-request {
  display: block;
}
```

I tried to use this pattern to make an invisible infinite scroll trigger element that is its own `htmx-indicator`.
