### ISSUE TITLE
Indicator Display Style Variations

### ISSUE THREAD

**Issue by lesichkovm** [bigskysoftware/htmx#3142]
At the moment, the hx-indicator uses the visibility: hidden style. Unlike display: none, the visibility style maintains the element's width, which can be undesirable in certain scenarios. For instance, when used within buttons, the hidden indicator can still occupy space, affecting the button's appearance.

To address this, many developers resort to additional styling like this:

```css
.htmx-indicator {
    display: none;
}

.htmx-request .htmx-indicator {
    display: inline-block;
}

.htmx-request.htmx-indicator {
    display: inline-block;
}
```

This approach works, but it can be cumbersome and add unnecessary complexity to your stylesheets.

I propose creating variations of the hx-indicator class to offer more flexibility:

  - hx-indicator: Retains the current visibility: hidden style.
  - hx-indicator-block: Uses display: block.
  - hx-indicator-inline: Uses display: inline-block.

This approach provides developers with more control over the indicator's display behavior, making it easier to integrate smoothly into various design contexts.
