### ISSUE TITLE
Entries in Atom feed show author as "Unknown"

### ISSUE THREAD

**Issue by williamjacksn** [bigskysoftware/htmx#3155]
Today I noticed that all entries in the Atom feed at https://htmx.org/atom.xml have the author listed as "Unknown".

```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
    <title>&lt;&#x2F;&gt; htmx - high power tools for html</title>
    <link rel="self" type="application/atom+xml" href="https://htmx.org/atom.xml"/>
    <link rel="alternate" type="text/html" href="https://htmx.org"/>
    <generator uri="https://www.getzola.org/">Zola</generator>
    <updated>2025-01-27T00:00:00+00:00</updated>
    <id>https://htmx.org/atom.xml</id>
    <entry xml:lang="en">
        <title>An interview with Chris Wanstrath aka @defunkt, Creator of pjax</title>
        <published>2025-01-27T00:00:00+00:00</published>
        <updated>2025-01-27T00:00:00+00:00</updated>
        
        <author>
          <name>
            
              Unknown
            
          </name>
        </author>
...
```

The [zola documentation][a] explains that the default feed template looks for the `authors` front matter variable, which is currently missing from all the site content.

[a]: https://www.getzola.org/documentation/templates/feeds/

For example, to show the author in the Atom feed, the front matter for `www/content/essays/interviews/chris_wanstrath.md` would need to be updated to:

```toml
+++
title = "An interview with Chris Wanstrath aka @defunkt, Creator of pjax"
date = 2025-01-27
updated = 2025-01-27
authors = ["Carson Gross"]
[taxonomies]
author = ["Carson Gross"]
tag = ["posts"]
+++
```

The `author` listed under the `[taxonomies]` section does not affect the Atom feed.
